apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  namespace: system-under-evaluation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      containers:
        - name: exporter
          image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.6.0
          ports:
            - containerPort: 9114
              name: metrics
          args:
            - "--es.uri=http://elasticsearch.system-under-evaluation.svc.cluster.local:9200"
