apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  namespace: system-under-evaluation
  labels:
    app: elasticsearch-exporter
spec:
  ports:
    - name: metrics
      port: 9114
      targetPort: 9114
  selector:
    app: elasticsearch-exporter
