apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: system-under-evaluation
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  type: ClusterIP
