apiVersion: v2
name: oxn-platform
description: Umbrella chart for OXN platform
type: application
version: 1.0.0

dependencies:
  - name: frontend-module
    version: "latest"
    appVersion: 0.0.1
    repository: "file://./charts/frontend-chart"
  - name: backend-module
    version: 1.0.0
    repository: "file://./charts/backend-module"
    condition: backend-chart.enabled
  - name: backend-dev-chart
    version: 1.0.0
    repository: "file://./charts/backend-dev-chart"
    condition: backend-dev-chart.enabled
  - name: analysis-module
    version: 1.0.0
    repository: "file://./charts/analysis-chart"
