apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{"seccomp.security.alpha.kubernetes.io/pod":"docker/default"},"labels":{"app":"cadvisor"},"name":"cadvisor","namespace":"cadvisor"},"spec":{"selector":{"matchLabels":{"app":"cadvisor","name":"cadvisor"}},"template":{"metadata":{"labels":{"app":"cadvisor","name":"cadvisor"}},"spec":{"automountServiceAccountToken":false,"containers":[{"image":"gcr.io/cadvisor/cadvisor:v0.45.0","name":"cadvisor","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"800m","memory":"2000Mi"},"requests":{"cpu":"400m","memory":"400Mi"}},"volumeMounts":[{"mountPath":"/rootfs","name":"rootfs","readOnly":true},{"mountPath":"/var/run","name":"var-run","readOnly":true},{"mountPath":"/sys","name":"sys","readOnly":true},{"mountPath":"/var/lib/docker","name":"docker","readOnly":true},{"mountPath":"/dev/disk","name":"disk","readOnly":true}]}],"serviceAccountName":"cadvisor","terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/"},"name":"rootfs"},{"hostPath":{"path":"/var/run"},"name":"var-run"},{"hostPath":{"path":"/sys"},"name":"sys"},{"hostPath":{"path":"/var/lib/docker"},"name":"docker"},{"hostPath":{"path":"/dev/disk"},"name":"disk"}]}}}}
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  creationTimestamp: "2024-11-01T12:48:22Z"
  generation: 1
  labels:
    app: cadvisor
  name: cadvisor
  namespace: cadvisor
  resourceVersion: "27028327"
  uid: b3dda6f7-860d-4e0e-9f25-de7750dd032e
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cadvisor
      name: cadvisor
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cadvisor
        name: cadvisor
    spec:
      automountServiceAccountToken: false
      containers:
      - image: gcr.io/cadvisor/cadvisor:v0.45.0
        imagePullPolicy: IfNotPresent
        name: cadvisor
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 2000Mi
          requests:
            cpu: 400m
            memory: 400Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: var-run
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - mountPath: /dev/disk
          name: disk
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cadvisor
      serviceAccountName: cadvisor
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
          type: ""
        name: rootfs
      - hostPath:
          path: /var/run
          type: ""
        name: var-run
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /var/lib/docker
          type: ""
        name: docker
      - hostPath:
          path: /dev/disk
          type: ""
        name: disk
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
