jaeger:
  allInOne:
    enabled: false
  agent:
    enabled: false
  ingester:
    enabled: false
  provisionDataStore:
    cassandra: false
    elasticsearch: false
  storage:
    type: elasticsearch
    elasticsearch:
      host: elasticsearch.system-under-evaluation.svc.cluster.local
      port: 9200
      scheme: http
      indexPrefix: jaeger
  collector:
    enabled: true
    service:
      grpc:
        port: 14250
      http:
        port: 14268
      otlp:
        grpc:
          name: otlp-grpc
          port: 4317
        http:
          name: otlp-http
          port: 4318
  query:
    enabled: true
    service:
      type: ClusterIP
      port: 16686
      targetPort: query

components:
  flagd:
    resources:
      limits:
        memory: 1Gi
  product-catalog:
    resources:
      limits:
        memory: 1Gi
  load-generator:
    enabled: false
  checkout:
    resources:
      limits:
        memory: 1Gi
  frontend-proxy:
    resources:
      limits:
        memory: 1Gi
  email:
    resources:
      limits:
        memory: 1Gi
opentelemetry-collector:
  config:
    processors:
      probabilistic_sampler:
        sampling_percentage: 1
        hash_seed: 22
    service:
      pipelines:
        traces:
          processors:
            - memory_limiter
            - resource
            - transform
            - batch
            - probabilistic_sampler
  resources:
    limits:
      memory: 18Gi
prometheus:
  server:
    extraArgs:
      web.enable-lifecycle: ""
    persistentVolume:
      enabled: true
      storageClass: "openebs-hostpath"
      accessModes:
        - ReadWriteOnce
      size: 50Gi
    resources:
      limits:
        memory: 6Gi
#opensearch:
#  persistence:
#    enabled: true