jaeger:
  allInOne:
    resources:
      requests:
        memory: 5Gi
      limits:
        memory: 5Gi
components:
  flagd:
    resources:
      limits:
        memory: 1Gi
  productCatalogService:
    resources:
      limits:
        memory: 1Gi
  loadgenerator:
    enabled: false
  checkoutService:
    resources:
      limits:
        memory: 1Gi
  frontendProxy:
    resources:
      limits:
        memory: 1Gi
  emailService:
    resources:
      limits:
        memory: 1Gi
opentelemetry-collector:
    config:
      processors:
        probabilistic_sampler:
          sampling_percentage: 1
          hash_seed: 22
      service:
        pipelines:
          traces:
            processors:
            - memory_limiter
            - resource
            - transform
            - batch
            - probabilistic_sampler
    resources:
      limits:
        memory: 18Gi
prometheus:
  server:
    extraArgs:
      web.enable-lifecycle: ""
    persistentVolume:
      enabled: true
      storageClass: "openebs-hostpath"
      accessModes:
        - ReadWriteOnce
      size: 16Gi
    resources:
        limits:
          memory: 6Gi