services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./mnt:/mnt/oxn-data/experiments
    ports:
      - "2000:2000"
    environment:
      - PYTHONPATH=/backend

  