apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-backend-pv
  labels:
    type: local
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "openebs-hostpath"