apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: system-under-evaluation
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  type: ClusterIP
