apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-sa
      nodeSelector:
        app: oxn-host
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: BACKEND_URL
          value: "http://backend-module:8000"
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: analysis-datastore
          mountPath: /mnt/analysis-datastore
      volumes:
      - name: analysis-datastore
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-analysis-datastore-pvc
