apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: system-under-evaluation
  labels:
    role: locust-master
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      role: locust-master
      app: locust-master
  template:
    metadata:
      labels:
        role: locust-master
        app: locust-master
    spec:
      containers:
      - name: master
        image: locustio/locust
        args: ["--master", "--autostart", "--users", "{{ max_users }}", "--spawn-rate", "{{ spawn_rate }}", "--run-time", "{{ run_time }}", "--host", "http://{{ base_address }}:{{ port }}"]
        volumeMounts:
        - mountPath: /home/locust
          name: locust-scripts
        ports:
        - containerPort: 5557
          name: comm
        - containerPort: 5558
          name: comm-plus-1
        - containerPort: 8089
          name: web-ui
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
