apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: system-under-evaluation
  labels:
    role: locust-worker
    app: locust-worker
spec:
  replicas: {{ worker_replicas }}
  selector:
    matchLabels:
      role: locust-worker
      app: locust-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: locust-worker
        app: locust-worker
    spec:
      containers:
      - name: worker
        image: locustio/locust
        imagePullPolicy: Always
        args: ["--worker", "--master-host={{ master_host }}"]
        volumeMounts:
        - mountPath: /home/locust
          name: locust-scripts
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
