services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./internal/oxn:/mnt/oxn-data
      - ./internal/analysis:/mnt/analysis-datastore
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
