name: Build and Push Docker Image

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Change to frontend directory
      run: cd frontend

    - name: Build Docker image
      working-directory: ./frontend
      run: docker buildx build --platform linux/amd64,linux/arm64 -t morauen/oxn-frontend:latest .

    - name: Push Docker image
      run: docker push morauen/oxn-frontend:latest